const newsData = [
{ category: 'news', 
    date: '2025-05-09', 
    title: '习近平出席俄罗斯纪念苏联伟大卫国战争胜利80周年庆典', 
    desc: '新华社莫斯科5月9日电（记者 倪四义、丁得启）当地时间5月9日，俄罗斯举行盛大庆典，纪念苏联伟大卫国战争胜利80周年。国家主席习近平和来自世界20多个国家及国际组织领导人应邀出席庆典。', 
    link: '/news/docu/2025/5/习近平出席俄罗斯纪念苏联伟大卫国战争胜利80周年庆典.html' },
  { category: 'news', date: '2025-05-02', 
    title: 'Grand Theft Auto VI 推出时间现为 2026 年 5 月 26 日', 
    desc: 'Grand Theft Auto VI 现已定在 2026 年 5 月 26 日推出。', 
    link: '/news/docu/2025/5/grand-theft-auto-vi-is-now-coming-may-26-2026.html' },
    { category: 'science', date: '2025-04-29', 
    title: 'Qwen3：思深，行速', 
    desc: '我们的旗舰模型 Qwen3-235B-A22B 在代码、数学、通用能力等基准测试中，与 DeepSeek-R1、o1、o3-mini、Grok-3 和 Gemini-2.5-Pro 等顶级模型相比，表现出极具竞争力的结果。', 
    link: '/news/docu/2025/4/qwen3.html' },
    { category: 'Wiki', date: '2025-05-11', 
    title: '1942年河南饥荒', 
    desc: '1942－1943年河南大饥荒发生在中华民国河南省的重大饥荒。', 
    link: '/news/docu/2025/5/1942年河南饥荒.html' },
    { category: 'Wiki', date: '2025-05-11', 
    title: '三年困难时期', 
    desc: '三年困难时期，又称三年大饥荒、中国大饥荒、三年自然灾害，是指中华人民共和国于1959年—1961年间因为三面红旗运动而发生全国性饥荒的一段时期，也有学者将1958年、1962年划入饥荒时期。', 
    link: '/news/docu/2025/5/三年困难时期.html' },
    { category: 'Wiki', date: '2025-05-11', 
    title: '超英赶美', 
    desc: '超英赶美是中国共产党主席毛泽东于1958年前后提出的政治口号，口号包含钢产量15年超出英国及20年赶上美国两个目标。', 
    link: '/news/docu/2025/5/超英赶美.html' },
    { category: 'blog', date: '2025-05-11', 
    title: 'ZhangYonghao 张永豪（杖雍皓）的终端服务器', 
    desc: '这个网站是我第一个全英文的终端网站，与中文网站相比，它仍然具有挑战性。', 
    link: '/news/docu/2025/5/ZhangYonghao张永豪（杖雍皓）的终端服务器.html' },
    { category: 'Wiki', date: '2025-05-11', 
    title: '孙燕姿 Stefanie Sun Wikipedia', 
    desc: '孙燕姿（英语：Stefanie Sun，1978年7月23日—），新加坡华裔女歌手。2000年以同名专辑《孙燕姿》在台湾出道。', 
    link: '/news/docu/personage/StefanieSun/孙燕姿.html' },
    { category: 'Wiki', date: '2025-05-11', 
    title: '黄仁勋 Jensen Jen-hsun Huang Wikipedia', 
    desc: '黄仁勋（英语：Jensen Jen-hsun Huang，1963年2月17日—），是一位台湾裔美国籍企业家 、电机工程师，图形芯片公司NVIDIA（英伟达）的共同创办人暨首席执行官。', 
    link: '/news/docu/personage/JensenJen-hsunHuang/黄仁勋.html' },
    { category: 'Wiki', date: '2025-05-11', 
    title: '美国排华法案 The US Chinese Exclusion Act Wikipedia', 
    desc: '《排华法案》是议员Horace F. Page提出，美国总统切斯特·艾伦·阿瑟于1882年5月6日签署的一项法案，成为《美国法典》的一部分。美国两党人士均参与了对该法案的推动。此法案为1880年对《天津条约续增条约》的修订，允许美国暂停华人移民。国会根据修订的条约，很快就制定了这项法案。', 
    link: '/news/docu/wiki/The-US-Chinese-Exclusion-Act/美国排华法案.html' },
    { category: 'Wiki', date: '2025-05-12', 
    title: '襄阳职业技术学院信息技术学院大数据技术应用师资队伍', 
    desc: '襄阳职业技术学院信息技术学院大数据技术应用专业有很多优秀的老师，例如刘莉莉老师、史润润老师、蔡敏老师等。', 
    link: '/news/docu/wiki/Xiangyang-Vocational-and-Technical-College-Information-Technology-College/big-data.html' },
    { category: 'Wiki', date: '2025-05-12', 
    title: '在平凡工作岗位中做有担当的英雄 —— 记好教师刘莉莉', 
    desc: '刘莉莉是我院大数据技术专业研究室主任，从事专业教学工作18年来，通过不断地努力和耕耘，培养了1000余名计算机专业学生，将大数据技术专业建设成襄阳职业技术学院重点专业和国家产教融合试点专业。', 
    link: '/news/docu/wiki/Xiangyang-Vocational-and-Technical-College-Information-Technology-College/LiuLili.html' },
    { category: 'Wiki', date: '2025-05-12', 
    title: '心有温度 行有智慧 —— 记王朝霞老师追光的日子', 
    desc: '王朝霞老师从事职业教育工作二十二年，连续十九年担任班主任工作，期间指导和推荐多名学生参与国家级、省级专业竞赛活动，所带学生多次获得国家教育部、共青团中央、湖北省教育厅等表彰。', 
    link: '/news/docu/wiki/Xiangyang-Vocational-and-Technical-College-Information-Technology-College/WangZhaoxia.html' },
];
